#define PACKAGE_NAME "MHASH"
#define PACKAGE_TARNAME "mhash"
#define PACKAGE_VERSION "0.9.9"
#define PACKAGE_STRING "MHASH 0.9.9"
#define PACKAGE_BUGREPORT "mhash-devel@sourceforge.net"
#define PACKAGE "mhash"
#define VERSION "0.9.9"
#define MHASH_VERSION PROGRAM_VERSION
#define _GNU_SOURCE 1
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define PROTOTYPES 1
#define __PROTOTYPES 1
